services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: ./dockerFile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: 
    volumes:
      - ./docker/db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis_data:/data
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:  
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  mongodb:
    image: "mongo:latest" 
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo-data:/data/db

networks:
  app-network:
    driver: bridge